spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbook?serverTimezone=Asia/Seoul
    username: root
    password: Aaaa123$
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql:
      init:
        mode: always
        schema-locations: classpath*:initdata/${database}/schema.sql